# Age Prediction Analysis Configuration
# This file contains all configuration parameters for the analysis pipeline

# Network Analysis Configuration
network_analysis:
  ig_dir: "/path/to/integrated_gradients"
  model_prefix: "dev_age_model"
  num_models: 5
  yeo_atlas_path: "/path/to/yeo_atlas.csv"
  atlas_nifti_path: "/path/to/atlas.nii.gz"
  percentile: 95.0

# Brain-Behavior Correlation Analysis Configuration
brain_behavior:
  data_dir: "/path/to/behavioral_data"
  analyze_cmihbn_td: true
  analyze_adhd200_td: true
  correction_method: "fdr_bh"  # Options: fdr_bh, bonferroni, holm
  alpha: 0.05

# Feature Attribution Configuration
feature_attribution:
  enabled: true
  percentile: 95.0
  consensus_threshold: 0.5

# Data Paths
data_paths:
  # HCP-Dev (Discovery Cohort)
  hcp_dev:
    training_data_dir: "/path/to/hcp_dev_training_data"
    behavioral_data: "/path/to/hcp_dev_behavioral.csv"
  
  # TD Cohorts for Bias Correction
  td_cohorts:
    nki_rs_td: "/path/to/nki_rs_td_data.bin"
    adhd200_td: "/path/to/adhd200_td_data.bin"
    cmihbn_td: "/path/to/cmihbn_td_data.bin"
  
  # External Datasets for Testing
  external_datasets:
  nki_rs_td: "/path/to/nki_rs_td_fold_0.bin"
  adhd200_adhd: "/path/to/adhd200_adhd_fold_0.bin"
  cmihbn_adhd: "/path/to/cmihbn_adhd_fold_0.bin"
  adhd200_td: "/path/to/adhd200_td_fold_0.bin"
  cmihbn_td: "/path/to/cmihbn_td_fold_0.bin"
  abide_asd: "/path/to/abide_asd_fold_0.bin"
  stanford_asd: "/path/to/stanford_asd_fold_0.bin"
  
  # Comprehensive Brain-Behavior Analysis Datasets
  nki_rs_td:
    ig_csv: "/path/to/nki_cog_dev_features_IG_convnet_regressor_single_model_fold_0.csv"
    behavioral_data: "/path/to/8100_CAARS-S-S_20191009.csv"
  adhd200_adhd:
    ig_csv: "/path/to/adhd200_adhd_features_all_sites_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS_single_model_predictions.csv"
    behavioral_data: "/oak/stanford/groups/menon/deriveddata/public/adhd200/restfmri/timeseries/group_level/brainnetome/normz/adhd200_run-rest_brainnetome_mean_regMov-6param_wmcsf_dt1_bpf008-09_normz_246ROIs_nn.pklz"
  cmihbn_adhd:
    ig_csv: "/path/to/cmihbn_adhd_weidong_cutoffs_features_all_sites_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS_single_model_predictions.csv"
    behavioral_data: "/oak/stanford/groups/menon/projects/wdcai/2019_ADHD_NN/data/imaging/timeseries/CMIHBN/restfmri/timeseries/group_level/brainnetome/normz/"
    c3sr_data: "/oak/stanford/groups/menon/projects/mellache/2021_foundation_model/scripts/dnn/prepare_data/adhd/C3SR.csv"
  adhd200_td:
    ig_csv: "/path/to/adhd200_td_features_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS.csv"
    behavioral_data: "/oak/stanford/groups/menon/deriveddata/public/adhd200/restfmri/timeseries/group_level/brainnetome/normz/adhd200_run-rest_brainnetome_mean_regMov-6param_wmcsf_dt1_bpf008-09_normz_246ROIs_nn.pklz"
  cmihbn_td:
    ig_csv: "/path/to/cmihbn_td_features_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS.csv"
    behavioral_data: "/oak/stanford/groups/menon/projects/wdcai/2019_ADHD_NN/data/imaging/timeseries/CMIHBN/restfmri/timeseries/group_level/brainnetome/normz/"
    c3sr_data: "/oak/stanford/groups/menon/projects/mellache/2021_foundation_model/scripts/dnn/prepare_data/adhd/C3SR.csv"
  abide_asd:
    ig_csv: "/path/to/abide_asd_features_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS.csv"
    behavioral_data: "/oak/stanford/groups/menon/deriveddata/public/abide/restfmri/timeseries/group_level/brainnetome/normz/"
  stanford_asd:
    ig_csv: "/path/to/stanford_asd_features_IG_convnet_regressor_trained_on_hcp_dev_top_regions_wIDS.csv"
    behavioral_data: "/oak/stanford/groups/menon/projects/mellache/2021_foundation_model/scripts/dnn/prepare_data/stanford_autism/"

# Model Configuration
model:
  architecture: "ConvNet"
  learning_rate: 0.001
  batch_size: 32
  num_epochs: 100
  dropout_rate: 0.6

# Plotting Configuration
plotting:
  figure_format: "png"  # Options: png, pdf, svg
  dpi: 300
  style: "white"
  color_palette: "default"

# Output Configuration
output:
  save_figures: true
  save_tables: true
  save_models: true
  create_summary_report: true
